[package]
name = "neo-fortune"
version = "0.1.0"
authors = ["David Knaack <davidkna@users.noreply.github.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
name = "neo-fortune"
path = "src/main.rs"
required-features = ["build-binary"]

[features]
default = ["build-binary"]
build-binary = [
    "ansi_term",
    "cowsay",
    "directories",
    "flate2",
    "lolcat",
    "reqwest",
    "structopt",
    "tar",
]

[dependencies]
# Lib
memchr = "2.2.1"
rand = { version = "0.7.0", features = ["std", "small_rng"] }

# Binary
directories = { version = "2.0.2", optional = true }
structopt =  { version = "0.3.7", optional = true }

# Download
flate2 = { version = "1.0", optional = true, default-features = false, features = ["rust_backend"] }
reqwest = { version = "0.10", optional = true, default-features = false, features = ["rustls-tls", "blocking"] }
tar = { version = "0.4.26", optional = true }

[dependencies.cowsay]
git = "https://github.com/davidkna/cowsay-rs"
optional = true
default-features = false

[dependencies.lolcat]
git = "https://github.com/davidkna/lolcat-rs"
optional = true
default-features = false

[target.'cfg(windows)'.dependencies]
ansi_term = { version = "0.12", optional = true }
